name: Main workflow

on:
  pull_request:
  push:
  schedule:
    # Prime the caches every Monday
    - cron: 0 1 * * MON

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        os:
          - ubuntu-latest
        ocaml-compiler:
          - ocaml-variants.5.0.0+trunk
        local-packages:
          - lwt_domain.opam

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Use OCaml ${{ matrix.ocaml-compiler }}
        uses: ocaml/setup-ocaml@v2
        with:
          ocaml-compiler: ${{ matrix.ocaml-compiler }}
          opam-depext-flags: --with-test
          opam-local-packages: ${{ matrix.local-packages }}

      - run: opam install lwt_domain --deps-only --with-test

      - run: opam exec -- dune build --only-packages lwt_domain

      - run: opam exec -- dune runtest --only-packages lwt_domain
